### ISSUE TITLE
TypeError: Expected cv::UMat for argument 'dst'

### ISSUE THREAD

**Issue by dwisatriow** [muchlisinadi/ALPR-Indonesian-plate#4]
Hi, i tried to recognize an image with this command `python Main.py -i ./car_test.png`, but get the following error. Any workaround please?

> Traceback (most recent call last):
  File "Main.py", line 270, in <module>
    main()
  File "Main.py", line 152, in main
    imgOriginalScene = imutils.transform (imgOriginalScene)
  File "/home/Rio/Program/ALPR-Indonesian-plate/imutils.py", line 75, in transform
    transformed  = cv2.warpPerspective(image, M, (imwidth,imheight),cv2.INTER_CUBIC or cv2.WARP_INVERSE_MAP)
TypeError: Expected cv::UMat for argument 'dst'

**Comment by muchlisinadi** [comment]
what opencv version do you use? last time I use version 3.4
